# spring.datasource.url=jdbc:mysql://localhost:3306/smart_inventory?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# spring.datasource.username=root
# spring.datasource.password=root123
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# # # NO flushMode line!


# #spring.datasource.url=jdbc:postgresql://dpg-d6of9nlm5p6s73d9pq8g-a/cab_kzxo





# #spring.datasource.username=cab_kzxo_user
# #spring.datasource.password=1EMpAmZbcYu8pw75IWTrnuE6BYAoHCfo


spring.datasource.url=jdbc:mysql://localhost:3306/smart_inventory?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# # # NO flushMode line!

# Local dev with H2 (embedded DB)
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.h2.console.enabled=true

server.port=${PORT:8080}